spring.application.name=banking-api
server.port=8080

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=bank-db;encrypt=true;trustServerCertificate=true
spring.datasource.username=Scott
spring.datasource.password=tiger

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
springdoc.swagger-ui.path=/swagger-ui.html

